/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Armors } from './armors';
import { Money } from './money';
import { Skills } from './skills';
import { Levels } from './levels';
import { Resources } from './resources';
import { Identities } from './identities';
import { Statistics } from './statistics';


export interface Character { 
    identities?: Array<Identities>;
    resources?: Array<Resources>;
    levels?: Array<Levels>;
    armors?: Array<Armors>;
    skills?: Array<Skills>;
    statistics?: Array<Statistics>;
    money?: Money;
}

